<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import AppLayout from '../../components/layout/AppLayout.vue'
import BaseCard from '../../components/ui/BaseCard.vue'
import { managementService } from '../../services/management/service'
const route = useRoute(); const router = useRouter(); const id = route.params.id ? Number(route.params.id) : null
const editing = Boolean(id); const loading = ref(editing); const submitting = ref(false); const error = ref('')
const form = reactive({ nom: '', sigle: '', numero_agrement: '', adresse: '', ville: '', telephone: '', email: '', description: '', responsable_id: null as number | null })
onMounted(async () => { if (!id) return; try { Object.assign(form, await managementService.getCooperative(id)) } catch (e: any) { error.value = e?.response?.data?.detail || 'Impossible de charger cette coopérative.' } finally { loading.value = false } })
async function submit() { if (submitting.value) return; submitting.value = true; error.value = ''; try { if (id) await managementService.updateCooperative(id, form); else await managementService.createCooperative(form); router.push('/cooperatives') } catch (e: any) { error.value = e?.response?.data?.detail || 'Enregistrement impossible.' } finally { submitting.value = false } }
</script>
<template><AppLayout><template #title>{{ editing ? 'Modifier la coopérative' : 'Nouvelle coopérative' }}</template>
<div class="page-intro"><div><p class="eyebrow">GESTION DES COOPÉRATIVES</p><h2>{{ editing ? 'Modifier la coopérative' : 'Ajouter une coopérative' }}</h2><p>Renseignez les informations de la coopérative puis enregistrez.</p></div><RouterLink class="secondary-button" to="/cooperatives">Retour à la liste</RouterLink></div>
<BaseCard><p v-if="loading" class="status-msg">Chargement…</p><p v-else-if="error" class="error-banner">{{ error }}</p><form v-else class="management-form form-page" @submit.prevent="submit">
<div class="field-group"><label for="coop-nom">Nom de la coopérative <span>*</span></label><input id="coop-nom" v-model="form.nom" required placeholder="Nom officiel" /></div><div class="field-group"><label for="coop-sigle">Sigle</label><input id="coop-sigle" v-model="form.sigle" placeholder="Ex. Cotisse" /></div><div class="field-group"><label for="coop-agrement">Numéro d’agrément</label><input id="coop-agrement" v-model="form.numero_agrement" placeholder="Numéro d’agrément ou NIF" /></div><div class="field-group"><label for="coop-adresse">Adresse</label><input id="coop-adresse" v-model="form.adresse" placeholder="Adresse du siège" /></div><div class="field-group"><label for="coop-ville">Ville</label><input id="coop-ville" v-model="form.ville" placeholder="Ville" /></div><div class="field-group"><label for="coop-telephone">Téléphone</label><input id="coop-telephone" v-model="form.telephone" placeholder="Téléphone de contact" /></div><div class="field-group"><label for="coop-email">Adresse email</label><input id="coop-email" v-model="form.email" type="email" placeholder="contact@exemple.com" /></div><div class="field-group field-wide"><label for="coop-description">Description</label><textarea id="coop-description" v-model="form.description" placeholder="Informations complémentaires"></textarea></div>
<div class="form-actions"><button class="primary-button compact-button" type="submit" :disabled="submitting">{{ submitting ? 'Enregistrement…' : 'Enregistrer' }}</button><RouterLink class="secondary-button" to="/cooperatives">Annuler</RouterLink></div></form></BaseCard></AppLayout></template>
