<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import AppLayout from '../../components/layout/AppLayout.vue'
import BaseCard from '../../components/ui/BaseCard.vue'
import { managementService } from '../../services/management/service'
const route = useRoute(); const router = useRouter(); const id = route.params.id ? Number(route.params.id) : null
const editing = Boolean(id); const loading = ref(editing); const submitting = ref(false); const error = ref('')
const form = reactive({ nom: '', adresse: '', ville: '', region: '', telephone: '', email: '', description: '', latitude: null as number | null, longitude: null as number | null })
onMounted(async () => { if (!id) return; try { Object.assign(form, await managementService.getGare(id)) } catch (e: any) { error.value = e?.response?.data?.detail || 'Impossible de charger cette gare.' } finally { loading.value = false } })
async function submit() { if (submitting.value) return; submitting.value = true; error.value = ''; try { if (id) await managementService.updateGare(id, form); else await managementService.createGare(form); router.push('/gares') } catch (e: any) { error.value = e?.response?.data?.detail || 'Enregistrement impossible.' } finally { submitting.value = false } }
</script>
<template><AppLayout><template #title>{{ editing ? 'Modifier la gare' : 'Nouvelle gare' }}</template>
<div class="page-intro"><div><p class="eyebrow">GESTION DES GARES</p><h2>{{ editing ? 'Modifier la gare routière' : 'Ajouter une gare routière' }}</h2><p>Renseignez les informations de la gare puis enregistrez.</p></div><RouterLink class="secondary-button" to="/gares">Retour à la liste</RouterLink></div>
<BaseCard><p v-if="loading" class="status-msg">Chargement…</p><p v-else-if="error" class="error-banner">{{ error }}</p><form v-else class="management-form form-page" @submit.prevent="submit">
<div class="field-group"><label for="gare-nom">Nom de la gare <span>*</span></label><input id="gare-nom" v-model="form.nom" required placeholder="Ex. Gare routière Anosibe" /></div><div class="field-group"><label for="gare-ville">Ville <span>*</span></label><input id="gare-ville" v-model="form.ville" required placeholder="Ex. Antananarivo" /></div><div class="field-group"><label for="gare-adresse">Adresse <span>*</span></label><input id="gare-adresse" v-model="form.adresse" required placeholder="Adresse complète" /></div><div class="field-group"><label for="gare-region">Région</label><input id="gare-region" v-model="form.region" placeholder="Région" /></div><div class="field-group"><label for="gare-telephone">Téléphone</label><input id="gare-telephone" v-model="form.telephone" placeholder="Téléphone de contact" /></div><div class="field-group"><label for="gare-email">Adresse email</label><input id="gare-email" v-model="form.email" type="email" placeholder="contact@exemple.com" /></div><div class="field-group"><label for="gare-latitude">Latitude</label><input id="gare-latitude" v-model.number="form.latitude" type="number" step="any" placeholder="-18.8792" /></div><div class="field-group"><label for="gare-longitude">Longitude</label><input id="gare-longitude" v-model.number="form.longitude" type="number" step="any" placeholder="47.5079" /></div><div class="field-group field-wide"><label for="gare-description">Description</label><textarea id="gare-description" v-model="form.description" placeholder="Informations complémentaires"></textarea></div>
<div class="form-actions"><button class="primary-button compact-button" type="submit" :disabled="submitting">{{ submitting ? 'Enregistrement…' : 'Enregistrer' }}</button><RouterLink class="secondary-button" to="/gares">Annuler</RouterLink></div></form></BaseCard></AppLayout></template>
