<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { RouterLink, useRoute } from 'vue-router'
import AppLayout from '../../components/layout/AppLayout.vue'
import BaseCard from '../../components/ui/BaseCard.vue'
import { destinationService } from '../../services/destination/service'
import { itineraireService } from '../../services/itineraire/service'
import { tarifService } from '../../services/tarif/service'
import { cooperativeService } from '../../services/cooperative/service'
import { userError } from '../../utils/errors'
import { useAuthenticationStore } from '../../stores/authentication/store'

const route = useRoute(); const id = Number(route.params.id)
const auth = useAuthenticationStore()
const section = computed(() => String(route.name).startsWith('destination') ? 'destinations' : String(route.name).startsWith('itineraire') ? 'itineraires' : 'tarifs')
const item = ref<any | null>(null); const associations = ref<any[]>([]); const fares = ref<any[]>([]); const cooperatives = ref<any[]>([]); const selectedCooperative = ref<number | null>(null); const loading = ref(true); const error = ref(''); const success = ref(''); const busy = ref(false)
const canAssociate = computed(() => auth.hasPermission('ITINERAIRE_COOPERATIVE_MANAGE'))
function showError(value: unknown, fallback: string) { error.value = userError(value, fallback, 'ROUTES_DETAIL_ERROR'); success.value = '' }
function formatDate(value?: string | null) { return value ? new Date(value).toLocaleDateString('fr-FR') : '-' }
async function load() { loading.value = true; try { item.value = section.value === 'destinations' ? await destinationService.get(id) : section.value === 'itineraires' ? await itineraireService.get(id) : await tarifService.get(id); if (section.value === 'itineraires') { associations.value = await itineraireService.listCooperatives(id); fares.value = await tarifService.history(id); cooperatives.value = (await cooperativeService.listCooperatives({ page: 1, page_size: 100, sort_by: 'nom', sort_order: 'asc' })).items } } catch (value: unknown) { showError(value, 'Impossible de charger le detail.') } finally { loading.value = false } }
async function attach() { if (!selectedCooperative.value || busy.value) return; busy.value = true; try { const value = await itineraireService.attach(id, selectedCooperative.value); associations.value = [...associations.value.filter(item => item.id_cooperative !== value.id_cooperative), value]; selectedCooperative.value = null; success.value = 'Cooperative associee avec succes.' } catch (value: unknown) { showError(value, 'Association impossible.') } finally { busy.value = false } }
async function detach(cooperativeId: number) { if (busy.value) return; busy.value = true; try { await itineraireService.detach(id, cooperativeId); const value = associations.value.find(item => item.id_cooperative === cooperativeId); if (value) value.is_active = false; success.value = 'Association desactivee.' } catch (value: unknown) { showError(value, 'Desassociation impossible.') } finally { busy.value = false } }
onMounted(load)
</script>

<template><AppLayout><template #title>Details {{ section }}</template><div class="page-intro"><div><p class="eyebrow">RESEAU & TARIFICATION</p><h2>Details {{ section }}</h2><p>Consultez toutes les informations rattachees.</p></div><div class="form-actions"><RouterLink class="secondary-button" :to="`/${section}`">Retour a la liste</RouterLink><RouterLink v-if="item" class="primary-button compact-button" :to="`/${section}/${id}/edit`">Modifier</RouterLink></div></div><p v-if="loading" class="status-msg">Chargement...</p><p v-else-if="error && !item" class="error-banner">{{ error }}</p><template v-if="item"><p v-if="error" class="error-banner">{{ error }}</p><p v-if="success" class="success-banner">{{ success }}</p><BaseCard><div class="card-heading"><div><h2>{{ section === 'destinations' ? item.nom : section === 'itineraires' ? `${item.destination_depart?.nom} - ${item.destination_arrivee?.nom}` : `Tarif #${item.id}` }}</h2><p><span :class="['status-badge', item.is_active ? 'active' : 'inactive']">{{ item.is_active ? 'Actif' : 'Inactif' }}</span></p></div></div><div class="detail-grid"><template v-if="section === 'destinations'"><div class="detail-item"><span class="detail-label">Nom</span><strong>{{ item.nom }}</strong></div><div class="detail-item"><span class="detail-label">Region</span><strong>{{ item.region || '-' }}</strong></div><div class="detail-item detail-wide"><span class="detail-label">Description</span><strong>{{ item.description || '-' }}</strong></div></template><template v-else-if="section === 'itineraires'"><div class="detail-item"><span class="detail-label">Depart</span><strong>{{ item.destination_depart?.nom }}</strong></div><div class="detail-item"><span class="detail-label">Arrivee</span><strong>{{ item.destination_arrivee?.nom }}</strong></div><div class="detail-item"><span class="detail-label">Distance</span><strong>{{ item.distance_km ?? '-' }} km</strong></div><div class="detail-item"><span class="detail-label">Duree estimee</span><strong>{{ item.duree_estimee_minutes ?? '-' }} minutes</strong></div></template><template v-else><div class="detail-item"><span class="detail-label">Prix</span><strong>{{ item.prix }} {{ item.devise }}</strong></div><div class="detail-item"><span class="detail-label">Portee</span><strong>{{ item.cooperative?.nom || 'Generale' }}</strong></div><div class="detail-item"><span class="detail-label">Periode</span><strong>{{ formatDate(item.date_debut) }} - {{ formatDate(item.date_fin) }}</strong></div></template></div></BaseCard>
<template v-if="section === 'itineraires'"><BaseCard><div class="card-heading"><div><h2>Cooperatives autorisees ({{ associations.length }})</h2><p>Les associations actives permettent de definir un tarif specifique.</p></div></div><form v-if="canAssociate" class="management-form inline-form" @submit.prevent="attach"><select v-model="selectedCooperative" required><option :value="null">Choisir une cooperative</option><option v-for="coop in cooperatives.filter(value => !associations.some(item => item.id_cooperative === value.id && item.is_active))" :key="coop.id" :value="coop.id">{{ coop.nom }}</option></select><button class="primary-button compact-button" :disabled="busy || !selectedCooperative">Associer</button></form><div v-if="associations.length" class="table-scroll"><table class="data-table"><caption>Autorisations des cooperatives</caption><thead><tr><th>Cooperative</th><th>Debut</th><th>Fin</th><th>Statut</th><th v-if="canAssociate">Action</th></tr></thead><tbody><tr v-for="association in associations" :key="association.id_cooperative"><td>{{ association.cooperative?.nom || association.id_cooperative }}</td><td>{{ formatDate(association.date_debut) }}</td><td>{{ formatDate(association.date_fin) }}</td><td><span :class="['status-badge', association.is_active ? 'active' : 'inactive']">{{ association.is_active ? 'Active' : 'Inactive' }}</span></td><td v-if="canAssociate"><button v-if="association.is_active" class="table-action danger-action" :disabled="busy" @click="detach(association.id_cooperative)">Desactiver</button></td></tr></tbody></table></div><div v-else class="empty-state">Aucune cooperative autorisee.</div></BaseCard><BaseCard><div class="card-heading"><div><h2>Historique des tarifs ({{ fares.length }})</h2><p>Les anciens tarifs restent consultables apres desactivation.</p></div></div><div v-if="fares.length" class="table-scroll"><table class="data-table"><caption>Historique des tarifs de l itineraire</caption><thead><tr><th>Portee</th><th>Prix</th><th>Debut</th><th>Fin</th><th>Statut</th></tr></thead><tbody><tr v-for="fare in fares" :key="fare.id"><td>{{ fare.cooperative?.nom || 'General' }}</td><td>{{ fare.prix }} {{ fare.devise }}</td><td>{{ formatDate(fare.date_debut) }}</td><td>{{ formatDate(fare.date_fin) }}</td><td>{{ fare.is_active ? 'Actif' : 'Inactif' }}</td></tr></tbody></table></div><div v-else class="empty-state">Aucun tarif enregistre.</div></BaseCard></template></template></AppLayout></template>
