<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { RouterLink, useRoute } from 'vue-router'
import AppLayout from '../../components/layout/AppLayout.vue'
import BaseCard from '../../components/ui/BaseCard.vue'
import { reservationService } from '../../services/reservation/service'
import type { Reservation, ReservationStatus } from '../../models/reservation/model'
import { useAuthenticationStore } from '../../stores/authentication/store'
import { userError } from '../../utils/errors'
const route = useRoute(); const auth = useAuthenticationStore(); const item = ref<Reservation | null>(null); const loading = ref(true); const busy = ref(false); const error = ref(''); const success = ref('')
const labels: Record<ReservationStatus, string> = { EN_ATTENTE: 'En attente', CONFIRMEE: 'Confirmée', PAYEE: 'Payée', ANNULEE: 'Annulée', EXPIREE: 'Expirée', EMBARQUEE: 'Embarquée', TERMINEE: 'Terminée' }
function showError(value: unknown, fallback: string) { error.value = userError(value, fallback, 'RESERVATION_DETAIL_ERROR') }
async function load() { try { item.value = await reservationService.get(Number(route.params.id)) } catch (value: unknown) { showError(value, 'Impossible de charger la réservation.') } finally { loading.value = false } }
async function change(action: 'confirm' | 'cancel') { if (!item.value || busy.value) return; busy.value = true; error.value = ''; try { item.value = action === 'confirm' ? await reservationService.confirm(item.value.id) : await reservationService.cancel(item.value.id); success.value = action === 'confirm' ? 'Réservation confirmée et billets générés.' : 'Réservation annulée.' } catch (value: unknown) { showError(value, 'Opération impossible.') } finally { busy.value = false } }
const canUpdate = () => auth.hasPermission('RESERVATION_UPDATE'); const canCancel = () => auth.hasPermission('RESERVATION_CANCEL')
onMounted(load)
</script>
<template><AppLayout><template #title>Détail réservation</template><div class="page-intro"><div><p class="eyebrow">VENTES & PLACES</p><h2>Détail de la réservation</h2><p>Réservation {{ item?.numero_reservation || `#${route.params.id}` }}</p></div><RouterLink class="secondary-button" to="/reservations">Retour à la liste</RouterLink></div><p v-if="loading" class="status-msg">Chargement…</p><p v-else-if="error" class="error-banner">{{ error }}</p><template v-if="item"><p v-if="success" class="success-banner">{{ success }}</p><BaseCard><div class="card-heading"><div><h2>{{ item.numero_reservation }}</h2><span class="status-badge active">{{ labels[item.statut] || item.statut }}</span></div></div><div class="detail-grid"><div class="detail-item"><span class="detail-label">Départ</span><strong>#{{ item.id_depart }}</strong></div><div class="detail-item"><span class="detail-label">Date</span><strong>{{ item.depart?.date_depart }} {{ item.depart?.heure_depart?.slice(0, 5) }}</strong></div><div class="detail-item"><span class="detail-label">Montant total</span><strong>{{ item.montant_total }}</strong></div><div class="detail-item"><span class="detail-label">Expiration</span><strong>{{ item.date_expiration ? new Date(item.date_expiration).toLocaleString('fr-FR') : '—' }}</strong></div></div><h3 class="section-title">Places et billets</h3><div class="table-scroll"><table class="data-table"><thead><tr><th>Place</th><th>Passager</th><th>Téléphone</th><th>Billet</th><th>Statut</th></tr></thead><tbody><tr v-for="place in item.places" :key="place.id"><td>{{ place.depart_place?.numero_place || place.id_depart_place }}</td><td>{{ place.nom_passager }}</td><td>{{ place.telephone_passager || '—' }}</td><td>{{ place.billet?.numero_billet || 'Billet non généré' }}</td><td>{{ place.billet?.statut || item.statut }}</td></tr></tbody></table></div><div class="form-actions"><button v-if="canUpdate() && item.statut === 'EN_ATTENTE'" class="primary-button" :disabled="busy" @click="change('confirm')">Confirmer</button><button v-if="canCancel() && !['ANNULEE', 'TERMINEE', 'EMBARQUEE'].includes(item.statut)" class="secondary-button danger-action" :disabled="busy" @click="change('cancel')">Annuler</button></div></BaseCard></template></AppLayout></template>
